apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-main
  labels:
    app: front-end-main
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: front-end-main
  template:
    metadata:
      labels:
        app: front-end-main
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: front-end-main
        image: docker.nexus.mathmarcoux.ca/__APPLICATION__:__TAG__
        ports:
        - containerPort: 3000

--- 
apiVersion: v1
kind: Service
metadata:
  name: front-end-main
  labels:
    app: front-end-main
spec:
  selector:
    app: front-end-main
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000