name: Build and Publish Release

on:
  push:
    tags:
      - v1.*

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.NEXUS_HOST }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.NEXUS_HOST }}/${{ github.repository }}:${{ github.ref_name }}

  deploy-to-production-infrastructure:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Replace Deployment Application Label
        shell: bash
        run: |
          sed -i 's|VAR_REPOSITORY|${{ github.repository }}|g' kubernetes/deployment.yml
          sed -i 's|VAR_TAG|${{ github.ref_name }}|g' kubernetes/deployment.yml
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f kubernetes/deployment.yml